language: objective-c

install:
  - bundle install --without=documentation

script:
  - xcodebuild test -project LXDeltaCalculation.xcodeproj -scheme LXDeltaCalculation -sdk iphonesimulator

after_success:
  - bundle exec slather
